#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

(cd src && ./Allwclean)
(cd applications && ./Allwclean)

find . -name log.Allwmake -delete

#------------------------------------------------------------------------------
