{
    Info<< "/*---------------------------------------------------------------------------*\\\n"
        << "|    newtonIcoFluid: standalone newtonIcoFoam solver for OpenFOAM            |\n"
        << "|                                                                             |\n"
        << "|    Extracted from solids4foam. For further information, see                 |\n"
        << "|    www.solids4foam.com.                                                     |\n"
        << "\\*---------------------------------------------------------------------------*/"
        << nl << endl;
}
