#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

echo; echo "Copying newtonIcoFluidScripts.sh to ${FOAM_USER_APPBIN}"; echo
\cp newtonIcoFluidScripts.sh ${FOAM_USER_APPBIN}/

#------------------------------------------------------------------------------
