#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
source newtonIcoFluidScripts.sh

newtonIcoFluid::caseDoesNotRunWithFoamExtend
newtonIcoFluid::caseDoesNotRunWithOpenFOAMOrg

wclean initialiseTaylorGreenVortex
(cd src && ./Allwclean)
cleanCase0
rm -rf constant/polyMesh dynamicCode
